name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Install the ssg tool
      run: dotnet tool install terevintosoftware.staticsitegenerator.tool --global
    - name: Build
      run: dotnet build . -c Release
    - name: Run the ssg tool
      run: ssg generate . --output ./out --route-casing KebabCase
